# SPDX-License-Identifier: GPL-2.0-only
name: "invoiceninja"
services:
  app:
    image: "pouncetech/invoiceninja:0.0.6-invoicev5.10.4"
    container_name: "invoiceninja"
    env_file: "config/.env"
    environment:
      APP_TYPE: "app"
      # CADDY_GLOBAL_OPTIONS: "debug" # enable Caddy debug messages
      CADDY_SERVER_EXTRA_DIRECTIVES: "tls internal" # used to generate untrusted HTTPS certificates
    restart: "unless-stopped"
    volumes:
      - "app_data:/app"
      - "caddy_config:/config"
      - "caddy_data:/data"
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    depends_on:
      - "app-upkeep"
      - "redis"
      - "db"
    networks:
      invoice_ninja:

  app-upkeep:
    image: "pouncetech/invoiceninja:0.0.6-invoicev5.10.4"
    container_name: "invoiceninja-upkeep"
    env_file: "config/.env"
    environment:
      APP_TYPE: "upkeep"
    restart: "unless-stopped"
    volumes:
      - "app_data:/app"
      - "./config/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "php /app/artisan schedule:work"]
      interval: 10s
      timeout: 3s
      retries: 6
    depends_on:
      - "redis"
      - "db"
    networks:
      invoice_ninja:

  db:
    image: "mariadb:11.3"
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "invoice_ninja"
      MYSQL_USER: "invoice_ninja"
      MYSQL_PASSWORD: "invoice_ninja"
    volumes:
      - "db_data:/var/lib/mysql"
      - "./config/sql_init.d:/docker-entrypoint-initdb.d"
    expose:
      - 3306
    networks:
      invoice_ninja:

  redis:
    image: "redis:7.2-alpine"
    restart: "unless-stopped"
    expose:
      - 6379
    networks:
      invoice_ninja:

volumes:
  app_data:
  caddy_data:
  caddy_config:
  db_data:

networks:
  invoice_ninja:
    name: "invoice_ninja"
    driver: "bridge"